name: Package and Release MD2PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    continue-on-error: true # Optional: remove this if you want the workflow to fail if one matrix element fails
    env:
      MATRIX_ARCH: ${{ matrix.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade setuptools wheel

    - name: Package app for Linux
      run: python setup.py sdist bdist_wheel --plat-name=manylinux1_${{ env.MATRIX_ARCH }}
      if: matrix.os == 'ubuntu-latest'

    - name: Package app for macOS
      run: python setup.py sdist bdist_wheel --plat-name=macosx_10_9_${{ env.MATRIX_ARCH }}
      if: matrix.os == 'macos-latest'

    - name: Create GitHub Release
      if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64' # Create release only once
      run: gh release create ${{ github.ref }} ./dist/*.tar.gz -t ${{ github.ref }} -n "Release ${{ github.ref }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Upload assets is not needed here anymore as `gh release create` already uploads them
